name: Cygwin Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Install Cygwin
        uses: egor-tensin/setup-cygwin@v3
        with:
          platform: x64
          packages: python38-numpy python38-pytest python38-hypothesis python38-cython
      - name: Install dependencies
        run: |
          python3.8 -m pip install --upgrade pip
          python3.8 -m pip install Cython numpy scipy
          python3.8 -m pip install -r requirements.txt
          python3.8 -m pip install -r requirements-test.txt
      - name: Test with pytest
        run: |
          python3.8 -m pip install pytest
          python3.8 -m pip install .
          python3.8 setup.py check
          python3.8 -m pytest
          python3.8 -m pytest --pyargs py_toeplitz --doctest-modules
