name: Cygwin Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup cache for Cygwin and pip
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/pip/
            C:\tools\cygwin\packages
          key: ${{ runner.os }}-build-${{ hashFiles('requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Install Cygwin
        id: install-cygwin
        uses: egor-tensin/setup-cygwin@v3
        with:
          platform: x64
          install-dir: 'C:\tools\cygwin'
          packages: python38-devel python38-numpy python38-pytest python38-hypothesis python38-cython python38-pip python38-wheel python38-setuptools
      - name: Clean Windows PATH
        uses: egor-tensin/cleanup-path@v1
        with:
          dirs: ${{ steps.install-cygwin.install-dir }}
      - name: Ask pip to use cache contents
        run: |
          mkdir -p ~/.config/pip
          bash -c "echo >~/.config/pip/pip.conf $'[install]\nprefer-binary = True'"
      - name: Install dependencies
        run: |
          python3.8 -m pip install --upgrade pip wheel
          python3.8 -m pip install Cython numpy scipy
          python3.8 -m pip install -r requirements.txt
          python3.8 -m pip install -r requirements-test.txt
      - name: Test with pytest
        run: |
          python3.8 -m pip install pytest
          python3.8 -m pip install .
          python3.8 setup.py check
          python3.8 -m pytest
          python3.8 -m pytest --pyargs py_toeplitz --doctest-modules
