name: Cygwin Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup cache for pip
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/pip/
          key: ${{ runner.os }}-build-${{ hashFiles('requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Install Cygwin
        id: install-cygwin
        uses: cygwin/cygwin-install-action@v2
        with:
          platform: x86_64
          install-dir: 'C:\cygwin'
          packages: >-
              python38-devel python38-numpy python38-pytest python38-hypothesis python38-cython python38-pip 
              python38-wheel python38-setuptools liblapack-devel libopenblas gcc-fortran gcc-g++
      - name: Clean Windows PATH
        uses: egor-tensin/cleanup-path@v1
        with:
          dirs: 'C:\cygwin\bin;C:\cygwin\lib\lapack'
      - name: Specify python version
        shell: bash.exe -eo pipefail -o igncr "{0}"
        run: |
          /usr/sbin/alternatives --set python /usr/bin/python3.8
          /usr/sbin/alternatives --set python3 /usr/bin/python3.8
      - name: Ask pip to use cache contents
        shell: bash.exe -eo pipefail -o igncr "{0}"
        run: |
          mkdir -p ~/.config/pip
          echo >~/.config/pip/pip.conf $'[install]\nprefer-binary = True'
      - name: Install build dependencies
        shell: bash.exe -eo pipefail -o igncr "{0}"
        env:
          BLAS: /usr/lib/libblas.dll.a
          LAPACK: /usr/lib/liblapack.dll.a
          NPY_LAPACK_ORDER: openblas,lapack
          NPY_BLAS_ORDER: openblas,blas
          NPY_BLAS_LIBS: -lblas
          NPY_LAPACK_LIBS: -llapack -lblas
        run: |
          python3.8 -m pip install --upgrade pip wheel 'setuptools<60'
          python3.8 -m pip install cython pythran pybind11
          python3.8 -m pip install 'numpy!=1.21.*'
      - name: Check NumPy import
        shell: bash.exe -eo pipefail -o igncr "{0}"
        run: |
          ls -l $(find /usr/local/lib/python3.8/site-packages/numpy/ -name \*.dll)
          file $(find /usr/local/lib/python3.8/site-packages/numpy/ -name \*.dll)
          cygcheck $(find /usr/local/lib/python3.8/site-packages/numpy/ -name \*.dll)
          ldd $(find /usr/local/lib/python3.8/site-packages/numpy/ -name \*.dll)
          python3.8 -v -c "import numpy as np; print(np.__version__)"
          python3.8 -v -c "import numpy.linalg as la"
          python3.8 -v -c "import numpy.linalg.lapack_lite"
      - name: Install more dependencies
        shell: bash.exe -eo pipefail -o igncr "{0}"
        env:
          BLAS: /usr/lib/libblas.dll.a
          LAPACK: /usr/lib/liblapack.dll.a
          NPY_LAPACK_ORDER: openblas,lapack
          NPY_BLAS_ORDER: openblas,blas
          NPY_BLAS_LIBS: -lblas
          NPY_LAPACK_LIBS: -llapack -lblas
        run: |
          python3.8 -m pip install 'scipy!=1.6.*,!=1.7.*,!=1.8.*'
          python3.8 -m pip install -r requirements.txt
          python3.8 -m pip install -r requirements-test.txt
      - name: Build wheel
        shell: bash.exe -eo pipefail -o igncr "{0}"
        run: |
          python3.8 setup.py bdist_wheel
      - name: Install wheel
        shell: bash.exe -eo pipefail -o igncr "{0}"
        run: |
          python3.8 -m pip install dist/py_toeplitz*.whl
      - name: Check that pip installed the extensions
        shell: bash.exe -eo pipefail -o igncr "{0}"
        run: |
          python3.8 -m pip show py_toeplitz
          python3.8 -m pip show -f py_toeplitz | grep .dll
          site_packages=$(python3.8 -m pip show py_toeplitz | grep Location | cut -d " " -f 2 -);
          dll_list=$(for name in $(python3.8 -m pip show -f py_toeplitz | grep -F .dll); do echo ${site_packages}/${name}; done)
          ls -l ${dll_list}
          file ${dll_list}
          ldd ${dll_list}
          cygcheck ${dll_list}
          for name in ${dll_list};
          do
              python3.8 -c "import "$(echo ${name} | sed -E -e "s|/home.*?site-packages/||g" -e "s|/|.|g" -e "s/.cpython-3.*-x86(_64)?-cygwin.dll//g")
          done
      - name: Test with pytest
        shell: bash.exe -eo pipefail -o igncr "{0}"
        run: |
          python3.8 -m pip install pytest
          python3.8 -m pip install .
          python3.8 setup.py check
          python3.8 -m pytest
          python3.8 -m pytest --pyargs py_toeplitz --doctest-modules
